// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxvbcgdldlipsdfewdgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4dmJjZ2RsZGxpcHNkZmV3ZGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODY4MzUsImV4cCI6MjA3MTA2MjgzNX0.OhgucHU8aNZpFYQ_Zv8aOz9XfUA2QkXTLaUttyFUDzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});